### ISSUE TITLE
De ruimte tussen titels en de inhoud

### ISSUE THREAD

**Issue by RobinStut** [sterrevangeest/web-app-from-scratch-18-19#1]
https://github.com/sterrevangeest/web-app-from-scratch-18-19/blob/a3770194169c6979ca0f0d81f0b6cbd28d4bd029/week1/public/js/xmlPromise.js#L42

Het is netter als er na de "titel:" een spatie komt zodat het beter leesbaar is

**Comment by sterrevangeest** [comment]
<img width="491" alt="schermafbeelding 2019-02-11 om 13 01 12" src="https://user-images.githubusercontent.com/32976396/52561938-24452d80-2dfd-11e9-8254-0467fc960844.png">
