### ISSUE TITLE
Font werkt niet

### ISSUE THREAD

**Issue by RobinStut** [sterrevangeest/web-app-from-scratch-18-19#2]
https://github.com/sterrevangeest/web-app-from-scratch-18-19/blob/a3770194169c6979ca0f0d81f0b6cbd28d4bd029/week1/public/css/styles.css#L3

Je font is op mijn computer niet te zien, misschien kan je google fonts gebruiken?

**Comment by sterrevangeest** [comment]
Moet nu werken. https://github.com/sterrevangeest/web-app-from-scratch-18-19/blob/6594dc2481f65cff2b5cbe43a4adb7032733117d/week1/index.html#L6-L9
