### ISSUE TITLE
Verberg api-key

### ISSUE THREAD

**Issue by DanielvandeVelde** [sterrevangeest/web-app-from-scratch-18-19#4]
https://github.com/sterrevangeest/web-app-from-scratch-18-19/blob/a3770194169c6979ca0f0d81f0b6cbd28d4bd029/week1/public/js/app.js#L46

Op dit moment is je api-key zichtbaar.
Je kan dit het beste even wijzigen aangezien dit gevoelige informatie is.
Hoe je dan kan doen is onder andere [hier](https://gist.github.com/derzorngottes/3b57edc1f996dddcab25) te vinden.

**Comment by sterrevangeest** [comment]
<img width="361" alt="schermafbeelding 2019-02-11 om 12 59 22" src="https://user-images.githubusercontent.com/32976396/52561865-e8aa6380-2dfc-11e9-82fe-eb67bc954f26.png">
