### ISSUE TITLE
Be consistent

### ISSUE THREAD

**Issue by maanlamp** [sterrevangeest/web-app-from-scratch-18-19#5]
https://github.com/sterrevangeest/web-app-from-scratch-18-19/blob/a3770194169c6979ca0f0d81f0b6cbd28d4bd029/week1/public/js/app.js#L59

You're using both `function` and `=>` all over the place. You should consider using only one of the two.

**Comment by sterrevangeest** [comment]
Only using `functions` now  https://github.com/sterrevangeest/web-app-from-scratch-18-19/commit/f42b1ee1c2939ab6da997633fc658430753948dc
