### ISSUE TITLE
Handle errors

### ISSUE THREAD

**Issue by maanlamp** [sterrevangeest/web-app-from-scratch-18-19#6]
https://github.com/sterrevangeest/web-app-from-scratch-18-19/blob/a3770194169c6979ca0f0d81f0b6cbd28d4bd029/week1/public/js/app.js#L48-L57

You have not supplied a `reject` function to the XHR. In the unfortunate event it fails, you will get weird errors. Try to use `XHMTLHttpRequest.onerror` to reject with proper errors.

**Comment by sterrevangeest** [comment]
handled the error
https://github.com/sterrevangeest/web-app-from-scratch-18-19/blob/f42b1ee1c2939ab6da997633fc658430753948dc/week1/public/js/xmlPromise.js#L18

_Originally posted by @sterrevangeest in https://github.com/sterrevangeest/web-app-from-scratch-18-19/issues/9#issuecomment-462310078_
