### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by TuriGuilano** [sterrevangeest/web-app-from-scratch-18-19#9]
You specify a reject param but you don't handle the error

https://github.com/sterrevangeest/web-app-from-scratch-18-19/blob/a3770194169c6979ca0f0d81f0b6cbd28d4bd029/week1/public/js/app.js#L48

**Comment by sterrevangeest** [comment]
handled the error
https://github.com/sterrevangeest/web-app-from-scratch-18-19/blob/f42b1ee1c2939ab6da997633fc658430753948dc/week1/public/js/xmlPromise.js#L18
